cc_library(
    name = "gpu_object_lifetime",
    srcs = ["gpu_object_lifetime.h"],
    visibility = ["//test:__subpackages__"]
)

filegroup(
    name = "expect_failure",
    srcs = ["expect_failure.sh"],
    visibility = ["//test:__subpackages__"]
)
