cc_library(
    name = "check_call_graphs",
    srcs = ["check_call_graphs.h"],
    visibility = ["//test:__subpackages__"],
)

filegroup(
    name = "expect_failure",
    srcs = ["expect_failure.sh"],
    visibility = ["//test:__subpackages__"],
)

cc_library(
    name = "gpu_object_lifetime_tracker",
    srcs = ["gpu_object_lifetime_tracker.h"],
    visibility = ["//test:__subpackages__"],
)
